"""rename department

Revision ID: 38b3e81c4b5b
Revises: b95003cecddd
Create Date: 2024-10-02 22:53:59.192485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b3e81c4b5b'
down_revision = 'b95003cecddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
